@startuml

[Grafana] as GR
[Prometheus] as PR

[API Gateway (NestJS)] as AG
database "Redis Cluster" as RDB
node RabbitMQ as MQ

[User Service (Go)] as US
database "User DB" as UDB
[Product Service (Go)] as PS
database "Product DB" as PDB
[Order Service (Go)] as OS
database "Order DB" as ODB
[ETL] as ETL
database "Warehouse" as DW

AG -right- RDB
AG --> US : gRPC
AG --> PS : gRPC
AG --> OS : gRPC

US -down- UDB
PS -down- PDB
OS -down- ODB

US <--> MQ : AMQP
PS <--> MQ : AMQP
OS <--> MQ : AMQP

GR -> PR : HTTP
PR -> AG : HTTP
PR --> US : HTTP
PR --> OS : HTTP
PR --> PS : HTTP

UDB <-- ETL
PDB <-- ETL
ODB <-- ETL

ETL - DW

@enduml