@startuml

[API Gateway (JS)] as AG
database "Redis Cache" as RDB
[Service Discovery (JS)] as SD
node RabbitMQ as MQ

[User Service (GO)] as US
database "User DB" as UDB
[Product Service (GO)] as PS
database "Product DB" as PDB
[Order Service (GO)] as OS
database "Order DB" as ODB

AG -left- RDB
AG --> US : gRPC
AG --> PS : gRPC
AG --> OS : gRPC

US -down- UDB
PS -down- PDB
OS - ODB

US <--> MQ : AMQP
PS <--> MQ : AMQP
OS <--> MQ : AMQP

AG .> SD
SD <.. US
SD <.. PS
SD <.. OS

@enduml