@startuml

[API Gateway (NestJS)] as AG
database "Redis Cache" as RDB
node RabbitMQ as MQ

[User Service (Go)] as US
database "User DB" as UDB
[Product Service (Go)] as PS
database "Product DB" as PDB
[Order Service (Go)] as OS
database "Order DB" as ODB

AG -right- RDB
AG --> US : gRPC
AG --> PS : gRPC
AG --> OS : gRPC

US -down- UDB
PS -down- PDB
OS - ODB

US <--> MQ : AMQP
PS <--> MQ : AMQP
OS <--> MQ : AMQP

@enduml