apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: marcelvlasenco/pad-labs-user:latest
        ports:
        - containerPort: 8080
        - containerPort: 8081
        # Add other configuration like dependencies and volumes as needed
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
  ports:
  - name: user-port-8080
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: user-port-8081
    protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: marcelvlasenco/pad-labs-product:latest
        ports:
        - containerPort: 8090
        - containerPort: 8091
        # Add other configuration like dependencies and volumes as needed
---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  selector:
    app: product
  ports:
  - name: product-port-8090
    protocol: TCP
    port: 8090
    targetPort: 8090
  - name: product-port-8091
    protocol: TCP
    port: 8091
    targetPort: 8091
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: marcelvlasenco/pad-labs-order:latest
        ports:
        - containerPort: 8070
        - containerPort: 8071
        # Add other configuration like dependencies and volumes as needed
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  ports:
  - name: order-port-8070
    protocol: TCP
    port: 8070
    targetPort: 8070
  - name: order-port-8071
    protocol: TCP
    port: 8071
    targetPort: 8071
  type: ClusterIP
