{
 "title": "Microservices Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Request Time 95 Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{job=\"user\"}[$__rate_interval])))",
     "legendFormat": "user service"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{job=\"product\"}[$__rate_interval])))",
     "legendFormat": "product service"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{job=\"order\"}[$__rate_interval])))",
     "legendFormat": "order service"
    }
   ]
  },
  {
   "title": "Gateway Resources",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_active_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grpc_server_msg_received_total{job=\"user\"}",
     "legendFormat": "{{job}} service"
    },
    {
     "expr": "grpc_server_msg_received_total{job=\"product\"}",
     "legendFormat": "{{job}} service"
    },
    {
     "expr": "grpc_server_msg_received_total{job=\"order\"}",
     "legendFormat": "{{job}} service"
    }
   ]
  },
  {
   "title": "Gateway Heap Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}